language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run test:coverage
- npm run compile
after_script:
- node ./node_modules/coveralls/bin/coveralls.js -v < ./coverage/lcov.info
deploy:
  - provider: npm
    skip_cleanup: true
    email: me@sburg.net
    api_key:
      secure: f8/n83wquTeDai4GljMLwozKsWJZ3PPTy0vLe4F4rOtQ8SOcar+R6PGd4ftgDFXybvfbLHa0FtmMoR4ZJhEPOZf9d6I22oxvOvvn6vYGn8VszX/fCqIH72hRSHmHGD5x8cMcjfzmzFt5wLmdwj8MKRyOk/C6a3FblB5HYvZep8n0hFuuKslwn3dKV4Q5FENoz+cspEwczt6chVwNok4BGDAtu8yr67hxtDyTkb4nnuMIkfj0tmWXww/zAFQuND2QthdRxER1ZjFYBhbrkZraFMMwPvCUZL3lNMrNrTIyuRk7r8IAxaOMsuPhugZ8mPtWQCG+DDDL/6qvCPG+IkRDOGRbvFi6krp+P1FNiVNBbADdRp5YYQGv9rJtE6uXK94rmWmK2iPwOXCqhno1C8ltClsjF8Q+OxRaVywTLr1tha2+vbzVMjrX0iZnllJex/kAfH/rWZKPoOnnJJEFzmLyHIHU3k5AzBK5gpzCO4Ds7d+W+zVBEZcsNPbf7fq/jIKl5dx3dx+bIu5pQbGxWk2a2zWPJ3Mwuy68+SNpCXJH/vXQ5tY2fRBUpjWEh5YGwyDCwj6aJbYsdJuXYLwS6uBY4yD4DMswCK2DBKUT9uei+ABdVk/b3mJfmpr9sP1wsGpN3mcfiWm1OHqC19N4xst7tspBJcXM34wVnlUsJBtGShU=
    on:
      tags: true
      branch: master
notifications:
  email:
    on_success: change
